# (macos and linux: ~/.config/rio/config.toml)
# (windows: C:\Users\USER\AppData\Local\rio\config.toml)
    padding-x = 0
    padding-y = [0,0]
    line-height = 1
    hide-mouse-when-typing = true
    ignore-selection-foreground-color = true
    confirm-before-quit = false
    #working-dir = "d:"

[cursor]
    shape = 'block'
    blinking = false

#[shell]
  #program = "nu"
  #args = [""]

[render]
    performance = "Low"
    backend = "Automatic"
    disable-unfocused-render=false
    max-fps=60

[window]
    width = 1000
    height = 600
    mode = "Windowed"
    opacity=1
    blur=true
    decorations = "Buttonless"

[fonts]
extras = [{ family = "文泉驿正黑" }]
size = 20
[fonts.regular]
family = "SauceCodePro Nerd Font Mono"
style = "normal"
weight = 400
[fonts.bold]
family = "SauceCodePro Nerd Font Mono"
style = "normal"
weight = 800
[fonts.italic]
family = "SauceCodePro Nerd Font Mono"
style = "italic"
weight = 400
[fonts.bold-italic]
family = "SauceCodePro Nerd Font Mono"
style = "italic"
weight = 800

[navigation]
# TopTab Plain BottomTab CollapsedTab NativeTab(Macos)
mode = "CollapsedTab"
clickable = false
use-current-path = false
color-automation = []

[developer]
log-level = "OFF"

[bindings]
  keys = [
    { key = "u", with = "Alt | Shift", action = "Scroll(3)"},
    { key = "d", with = "Alt | Shift", action = "Scroll(-3)"},
    
    { key = "u", with = "Control | Shift", action = "ScrollHalfPageUp"},
    { key = "d", with = "Control | Shift", action = "ScrollHalfPageDown"},

    { key = "a", with = "Alt | Shift", action = "IncreaseFontSize"},
    { key = "z", with = "Alt | Shift", action = "DecreaseFontSize"},
    { key = "r", with = "Alt | Shift", action = "ResetFontSize"},

    #{ key = "c", with = "Control | Shift", action = "None"  },
    #{ key = "v", with = "Control | Shift", action = "None"  },

    #{ key = "v", with = "Control | Shift", action = "Paste"},
    #{ key = "c", with = "Control | Shift", action = "Copy"},
    { key = "v", with = "Alt", action = "Paste"},
    { key = "c", with = "Alt", action = "Copy"},

    { key = "g", with = "Alt|Shift", action = "ToggleVIMode"},

    { key = "o", with = "Alt | Shift", action = "CreateTab"},
    { key = "c", with = "Alt | Shift", action = "CloseTab"},
    { key = "c", with = "Alt | Shift", action = "CloseTab"},
    { key = "x", with = "Alt | Shift", action = "CloseUnfocusedTabs"},

    { key = "p", with = "Alt | Shift", action = "SelectPrevTab"},
    { key = "n", with = "Alt | Shift", action = "SelectNextTab"},
    { key = "s", with = "Alt | Shift", action = "SplitHorizontally"},
    { key = "v", with = "Alt | Shift", action = "SplitVertically"},
    { key = "b", with = "Alt | Shift", action = "ClosePane"},

    { key = "f", with = "Alt | Shift", action = "SearchBackward"},
    { key = "b", with = "Alt | Shift", action = "SearchForward"},
    { key = "b", with = "Control | Shift", action = "SearchFocusNext"},
    { key = "b", with = "Control | Shift", action = "SearchFocusPrevious"},
]

[colors]
background = '#24283b'
foreground = '#c0caf5'
selection-background = '#364a82'
#selection-background = '#626880'
selection-foreground = '#c0caf5'
cursor    = '#c0caf5'
vi-cursor = '#364a82'

# Search
search-match-background = '#364a82'
search-match-foreground = '#c0caf5'
search-focused-match-background = '#c0caf5'
search-focused-match-foreground = '#FFFFFF'

# Navigation
tabs            = '#494c62'
tabs-active     = '#6a6e8e'
tabs-foreground = '#1d202f'
tabs-active-highlight  = '#6a6e8e'
tabs-active-foreground = '#1d202f'
bar = '#494c62'

# Color
black   = '#1d202f'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#bb9af7'
cyan    = '#7dcfff'
white   = '#a9b1d6'

dim-black   = '#1d202f'
dim-red     = '#f7768e'
dim-green   = '#9ece6a'
dim-yellow  = '#e0af68'
dim-blue    = '#7aa2f7'
dim-magenta = '#bb9af7'
dim-cyan    = '#7dcfff'
dim-white   = '#a9b1d6'

light_black   = '#414868'
light_red     = '#f7768e'
light_green   = '#9ece6a'
light_yellow  = '#e0af68'
light_blue    = '#7aa2f7'
light_magenta = '#bb9af7'
light_cyan    = '#7dcfff'
light_white   = '#c0caf5'
