[colors]
 cursor = {cursor = '#c0caf5',text = '#1d202f'}
 selection= { background = '#364a82',text = '#c0caf5' }
#selection= { background = '#626880',text = '#c0caf5' }
[colors.normal]
    black= '#414868'
    blue= '#7aa2f7'
    cyan= '#7dcfff'
    green= '#9ece6a'
    magenta= '#bb9af7'
    red= '#f7768e'
    white= '#c0caf5'
    yellow= '#e0af68'

[colors.bright]
    black= '#1d202f'
    blue= '#7aa2f7'
    cyan= '#7dcfff'
    green= '#9ece6a'
    magenta= '#bb9af7'
    red= '#f7768e'
    white= '#a9b1d6'
    yellow= '#e0af68'

[colors.primary]
    background= '#24283b'
    foreground='#c0caf5'


[font]

  normal={family= "SauceCodePro Nerd Font Mono",style=  "Regular"}
  italic={family= "SauceCodePro Nerd Font Mono",style=  "Italic"}
  bold=  {family="SauceCodePro Nerd Font Mono",style=  "Bold"}
  bold_italic={family= "SauceCodePro Nerd Font Mono",style=  "Bold Italic"}
  offset = {x=0,y=0}
  glyph_offset= {x=0,y=0}
  builtin_box_drawing = false
  size=20

[window]
  dimensions ={columns=80,lines=24}
  dynamic_title = false
  title = "Alacritty"
  padding = { x = 0, y = 0}
  dynamic_padding=false
  opacity = 1

[scrolling]
   history = 2000
   multiplier = 5

[keyboard]
bindings=[
{ key="c", mods="Alt",action="Copy"},
{ key="v", mods="Alt",action="Paste"},
{ key="c", mods="Shift|Control",action="Copy"},
{ key="v", mods="Shift|Control",action="Paste"},

{ key="a", mods="Shift|Alt",action="IncreaseFontSize"},
{ key="z", mods="Shift|Alt",action="DecreaseFontSize"},
{ key="r", mods="Shift|Alt",action="ResetFontSize"},

{ key="u", mods="Shift|Alt", action="ScrollLineUp"},
{ key="d", mods="Shift|Alt", action="ScrollLineDown"},
{ key="u", mods="Shift|Control",action="ScrollPageUp"},
{ key="d", mods="Shift|Control", action="ScrollPageDown"},

{ key="g", mods="Shift|Alt", action="ToggleViMode"},
{ key="f", mods="Shift|Alt", action="SearchForward"},
{ key="b", mods="Shift|Alt", action="SearchBackward"},
]

[mouse]
hide_when_typing = true

#[shell]
# program = "C:/Program Files/nu/bin/nu.exe"
# working_directory = "D://library"
